#!/data/data/com.termux/files/usr/bin/bash
#Created on 16/July/2017 by Ivam3
#Last update Agust/2018
#
#       Var
		red='\033[1;31m'
                green='\033[1;32m'
                yellow='\033[1;33m'
		blue='\033[1;34m'
		magenta='\033[1;35m'                              
		cyan='\033[1;36m'               
		reset='\033[0m'                     
                Noko=$(gem list nokogiri -i)

echo $(clear)
for i in  / - \ - \ - / - \ - / - \ - / -; do
        printf "$(clear) $cyan Upgrading Termux. . . .$i"
        sleep 1
done
echo "
"
printf "$reset"
apt update -y && apt upgrade -y
apt autoremove
echo "
"
printf "$green"
	echo "  ____                       _   _            _"
	echo " / ___|___  ___  __ _ _ __  | | | | __ _  ___| | __"
	echo "| |   / _ \/ __|/    |  __| | |_| |/ _  |/ __| |/ /"
	echo "| |__|  __/\__ \ (_| | |    |  _  | (_| | (__|   <"
	echo " \____\___||___/\__,_|_|    |_| |_|\__,_|\___|_|\_\"
$reset"
sleep 5
echo "
"
printf "Using And Installing This Tools That Mean You Ready For

$red[1] $yellow Use At Your Own Risk
$red[2] $yellow No Warranty
$red[3] $yellow If it violates the law with this tool the risk is borne by the user
"
printf "$green
-------------------------------------------
Are You Sure Want To Install Metasploit ?
-------------------------------------------
$reset
Press $green Enter$cyan if you Agree / Continue Install
Press $red CTRL + C$green if you Disagree / Cancel Install"
read ENTER  
echo "
"
printf "$cyan :::::::::: Removing old versions :::::::::: $reset
\n"
sleep 1  
find $HOME -name "*17.1.tar.gz" -type f -delete
find $HOME -name "metasploit*" -type d -exec rm -rf {} \;

#Fixing libxm12 not found error
$PREFIX/include/libxml2/libxml $PREFIX/include/
echo "
"
printf "$cyan :::::::::: Installing Metasploit repositories :::::::::: $yellow
\n"
apt install -y autoconf bison clang coreutils axel curl findutils git apr apr-util libffi-dev libgmp-dev libpcap-dev postgresql-dev readline-dev libsqlite-dev openssl-dev libtool libxml2-dev libxslt-dev ncurses-dev pkg-config wget make ruby-dev libgrpc-dev termux-tools ncurses-utils ncurses unzip zip tar postgresql termux-elf-cleaner
sleep 1
echo "
"
#Install metasploit-framework v.4.17.1
echo "
"
printf "$green :::::::::: Downloading Metasploit Framework v.4.17.1 :::::::::: $yellow
\n"
cd $HOME
curl -LO https://github.com/rapid7/metasploit-framework/archive/4.17.1.tar.gz
tar -xf $HOME/4.17.1.tar.gz
mv $HOME/metasploit-framework-4.17.1 $HOME/metasploit-framework
cd $HOME/metasploit-framework
sed '/rbnacl/d' -i Gemfile.lock
sed '/rbnacl/d' -i metasploit-framework.gemspec

#Installing gems
echo "
"
printf "$cyan :::::::::: Installing Ruby Gems :::::::::: $green
\n"
echo
gem install bundler
sed 's|nokogiri (1.*)|nokogiri (1.8.0)|g' -i Gemfile.lock

#Reviewing nokogiri gem
        if [ $Noko == "false" ]; then
                gem install nokogiri -v '1.8.0' -- --use-system-libraries
        else
                printf "$cyan Nokogiri ..... ok!!"
        fi
echo "
"
cd $HOME/metasploit-framework
bundle install -j5
$PREFIX/bin/find -type f -executable -exec termux-fix-shebang \{\} \;
rm ./modules/auxiliary/gather/http_pdf_authors.rb
        if [ -e $PREFIX/bin/msfconsole ]; then
                rm $PREFIX/bin/msfconsole
        fi

        if [ -e $PREFIX/bin/msfvenom ]; then
                rm $PREFIX/bin/msfvenom
        fi
ln -s $HOME/metasploit-framework/msfconsole /data/data/com.termux/files/usr/bin/
ln -s $HOME/metasploit-framework/msfvenom /data/data/com.termux/files/usr/bin/

termux-elf-cleaner /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/pg-0.20.0/lib/pg_ext.so

#Thanks to . . .

	echo "
	"
	printf "$yellow"
	echo " __  __      _                  _       _ _"
	echo "|  \/  | ___| |_ __ _ ___ _ __ | | ___ (_) |_"
	echo "| |\/| |/ _ \ __/ _  / __|  _ \| |/ _ \| | __|"
	echo "| |  | |  __/ || (_| \__ \ |_) | | (_) | | |_"
	echo "|_|  |_|\___|\__\__,_|___/ .__/|_|\___/|_|\__|(Cesar Hack Gray"
                        
	

#Creating data base
echo "
"
printf "$cyan :::::::::: Creating Postgresql Data Bases :::::::::: $reset
\n"
echo
cd $HOME/metasploit-framework/config
curl -LO https://raw.githubusercontent.com/ivam3/ivam3.github.io/master/master/database.yml
mkdir -p $PREFIX/var/lib/postgresql
initdb $PREFIX/var/lib/postgresql

pg_ctl -D $PREFIX/var/lib/postgresql start
createuser msf
createdb msf_database

#Fixed data base error
sed -i "4a pg_ctl -D $PREFIX/var/lib/postgresql start" $PREFIX/etc/bash.bashrc
sed -i "5a clear" $PREFIX/etc/bash.bashrc

#Intalling Ruby Gems Issues Resolve (RuGiR)
cd $HOME/metasploit-framework/
curl -LO https://raw.githubusercontent.com/ivam3/ivam3.github.io/master/master/RuGiR
chmod 777 $HOME/metasploit-framework/RuGiR

	if [ -e $HOME/MSF-mastering_the_framework ]; then
		rm -rf $HOME/MSF-mastering_the_framework
	else
		find $HOME -name "Downloadinstall_metasploit.sh" -type d -delete
	fi

	if [ -e $HOME/4.17.1.tar.gz ]; then
		rm $HOME/4.17.1.tar.gz
	fi

#Goodbye
echo $(clear)
printf "$cyan
###################################################################
$magenta
Cesar : creando base de datos.
                Now you can active it with . . .

pg_ctl -D $PREFIX/var/lib/postgresql start
$cyan
###################################################################
"
sleep 5
echo "
"
printf "$blue
..:::::::::..
                  ..:::aad8888888baa:::..
              .::::d:?88888888888?::8b::::.
            .:::d8888:?88888888??a888888b:::.
          .:::d8888888a8888888aa8888888888b:::.
         ::::dP::::::::88888888888::::::::Yb::::
        ::::dP:::::::::Y888888888P:::::::::Yb::::
       ::::d8:::::::::::Y8888888P:::::::::::8b::::
      .::::88::::::::::::Y88888P::::::::::::88::::.
      :::::Y8baaaaaaaaaa88P:T:Y88aaaaaaaaaad8P:::::
      :::::::Y88888888888P::|::Y88888888888P:::::::
      ::::::::::::::::888:::|:::888::::::::::::::::
      `:::::::::::::::8888888888888b::::::::::::::                            :::::::::::::::88888888888888::::::::::::::
        :::::::::::::d88888888888888:::::::::::::                                ::::::::::::88::88::88:::88::::::::::::
          `::::::::::88::88::88:::88::::::::::
            `::::::::88::88::P::::88::::::::
              `::::::88::88:::::::88::::::
                 ``::::::::Cesar:::::::
                      ``:::Hack::::
                   Cesar Hacker The Gray
             \n"
sleep 3
printf "$cyan :::::::::: Running Metasploit :::::::::: $reset
\n"

        if [ -e $PREFIX/bin/msfconsole ] && [ -e $PREFIX/bin/msfvenom ]; then
                echo
                cd $HOME/metasploit-framework
                printf "$yellow Let's try to run msfconsole
		\n"
                sleep 1
		msfconsole
        else
                echo
                cd $HOME/metasploit-framework
                printf "$yellow Let's try to run msfconsole
		\n"
                sleel 1
		ruby msfconsole
        fi

echo "
"
printf "$yellow aIf msfconsole or msfvenom didn't run
please execute the file RuGiR
(Ruby Gem issues Resolved)
to try to fix it with an other steps
cesar hack gray
$cyan => sh RuGiR
$green
\n"
cd $HOME
						#Cesar
